### ISSUE TITLE
panic while `OrderBy` on an empty slice

### ISSUE THREAD

**Issue by aisk** [ahmetalpbalkan/go-linq#42]
Codes:

```go
func main() {
	linq.From([]string{}).OrderBy(func(in interface{}) interface{} {
		return 0
	}).Results()
}
```

`OrderBy` on a non-empty slice which have a `Where` filter, and the filter will filter all the elements, will cause the bug too.

Stack trace:
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x437ce0, 0xc42000c0f0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/leancloud/lean-cli/lean/vendor/github.com/ahmetalpbalkan/go-linq.Query.sort(0xc420385170, 0xc42038ede0, 0x1, 0x1, 0xc42038edc0, 0x0, 0x743200)
	/Users/asaka/Codes/go/src/github.com/leancloud/lean-cli/lean/vendor/github.com/ahmetalpbalkan/go-linq/orderby.go:177 +0x235
github.com/leancloud/lean-cli/lean/vendor/github.com/ahmetalpbalkan/go-linq.Query.OrderBy.func1(0x45e5c0)
	/Users/asaka/Codes/go/src/github.com/leancloud/lean-cli/lean/vendor/github.com/ahmetalpbalkan/go-linq/orderby.go:28 +0x8d
github.com/leancloud/lean-cli/lean/vendor/github.com/ahmetalpbalkan/go-linq.Query.Results(0xc42038edc0, 0x546ec0, 0xc42038edc0, 0xc420385170)
	/Users/asaka/Codes/go/src/github.com/leancloud/lean-cli/lean/vendor/github.com/ahmetalpbalkan/go-linq/result.go:208 +0x2e
main.main()
	/Users/asaka/Codes/go/src/github.com/leancloud/lean-cli/lean/main.go:299 +0xf0
```

go-linq version:

```
- name: github.com/ahmetalpbalkan/go-linq
  version: 8985ec99e11a8bff7eb19dd0a0b2187770dab23a
```

(current master branch codes).

**Comment by ahmetalpbalkan** [comment]
cc: @kalaninja any ideas?

**Comment by kalaninja** [comment]
@aisk thanks for the bug report. I'll research it asap.

**Comment by kalaninja** [comment]
@ahmetalpbalkan @aisk Fixed in master branch

**Comment by aisk** [comment]
@kalaninja Cool, thanks!
